// =============================================================================
// Head-to-head — the published comparison table is generated, validated, and
// never renders a blank cell
// =============================================================================
// scripts/head-to-head.js measures GateTest, Semgrep and ESLint
// (eslint-plugin-security) on the pinned corpus and writes
// website/app/data/head-to-head.json; /precision renders it through
// website/app/lib/head-to-head.js — the one definition both sides import.
// This file is the control pair for that module, the committed JSON, the
// page's use of it, and the weekly workflow:
//
//   - the validator accepts the committed file and rejects every shape that
//     would render as a blank or as a number nobody measured
//   - the run-order and time-box helpers do what the script relies on
//   - buildTable never yields an empty cell — a tool that was not run, timed
//     out, was unavailable, or is not measured yet SAYS SO in the cell
//   - the committed JSON pins the same commits the corpus manifest pins and
//     never claims more repos than the corpus has
//   - the page imports the JSON and the table builder and types no count
//   - the workflow installs Semgrep with pip on ubuntu and runs the script
// =============================================================================

const { describe, it } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const LIB_PATH = path.join(ROOT, 'website', 'app', 'lib', 'head-to-head.js');
const JSON_PATH = path.join(ROOT, 'website', 'app', 'data', 'head-to-head.json');
const MANIFEST_PATH = path.join(ROOT, 'reliability-corpus', 'real-world.json');
const PAGE_PATH = path.join(ROOT, 'website', 'app', 'precision', 'page.tsx');
const SCRIPT_PATH = path.join(ROOT, 'scripts', 'head-to-head.js');
const WORKFLOW_PATH = path.join(ROOT, '.github', 'workflows', 'head-to-head.yml');

const h2h = require(LIB_PATH);
const script = require(SCRIPT_PATH);
const { validateHeadToHead, buildTable, orderRepos, limitRepos, elapsedSeconds, STATUS, TOOL_TIMEOUT_MS } = h2h;

const SHA = 'a'.repeat(40);

/** A document with every kind of null and non-ok status the script can write. */
function fixture(overrides = {}) {
  return {
    schemaVersion: 1,
    generatedAt: '2026-09-16T00:00:00.000Z',
    source: 'scripts/head-to-head.js',
    engineVersion: '1.61.1',
    suite: 'full',
    corpusSize: 20,
    tools: {
      gatetest: { version: '1.61.1' },
      semgrep: { version: null, reason: 'semgrep is not installed on this runner' },
      eslintSecurity: { version: null, reason: 'npm install failed' },
      sonarqube: { status: 'not measured', reason: 'needs a server' },
      codeql: { status: 'not measured', reason: 'needs a database build' },
    },
    repos: [
      {
        name: 'express', url: 'https://github.com/expressjs/express.git', sha: SHA, language: 'JavaScript',
        measuredAt: '2026-09-16T00:00:00.000Z',
        gatetest: { status: 'ok', blocking: 0, total: 13, seconds: 41.2 },
        semgrep: { status: 'tool unavailable on this runner', seconds: 0 },
        eslintSecurity: { status: 'timed out', seconds: 600.0 },
        codeql: { status: 'ok', blocking: 2, total: 9, seconds: 88.4, language: 'javascript' },
      },
      {
        name: 'django', url: 'https://github.com/django/django.git', sha: SHA, language: 'Python',
        measuredAt: '2026-09-16T00:00:00.000Z',
        gatetest: { status: 'timed out', seconds: 600.0 },
        semgrep: { status: 'ok', error: 3, warning: 40, info: 2, exit: 0, seconds: 120.5 },
        eslintSecurity: null,
        codeql: { status: 'not measured', seconds: 12.3, language: 'Python', reason: 'codeql database create failed (exit 1): some stderr tail' },
      },
      {
        name: 'gin', url: 'https://github.com/gin-gonic/gin.git', sha: SHA, language: 'Go',
        measuredAt: '2026-09-16T00:00:00.000Z',
        gatetest: { status: 'failed (exit 3)', seconds: 2.0 },
        semgrep: { status: 'failed (exit 2) — no JSON output', seconds: 9.9 },
        eslintSecurity: null,
        // no codeql key at all — a row from before this column existed
      },
    ],
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// The validator
// ---------------------------------------------------------------------------

describe('validateHeadToHead', () => {
  it('accepts a document with every kind of null and non-ok status', () => {
    assert.deepStrictEqual(validateHeadToHead(fixture()), []);
  });

  it('rejects a document that is not generated by the script', () => {
    const problems = validateHeadToHead(fixture({ source: 'typed by hand' }));
    assert.ok(problems.some((p) => /source/.test(p)), problems.join('\n'));
  });

  it('rejects an ok GateTest cell without its numbers', () => {
    const doc = fixture();
    doc.repos[0].gatetest = { status: 'ok', seconds: 1 };
    const problems = validateHeadToHead(doc);
    assert.ok(problems.some((p) => /gatetest\.blocking/.test(p)));
    assert.ok(problems.some((p) => /gatetest\.total/.test(p)));
  });

  it('rejects blocking above total', () => {
    const doc = fixture();
    doc.repos[0].gatetest = { status: 'ok', blocking: 5, total: 2, seconds: 1 };
    assert.ok(validateHeadToHead(doc).some((p) => /blocking exceeds total/.test(p)));
  });

  it('rejects an ok Semgrep cell without severities or an exit status', () => {
    const doc = fixture();
    doc.repos[1].semgrep = { status: 'ok', seconds: 1 };
    const problems = validateHeadToHead(doc);
    for (const k of ['error', 'warning', 'info', 'exit']) {
      assert.ok(problems.some((p) => new RegExp(`semgrep\\.${k}`).test(p)), `expected a problem about semgrep.${k}`);
    }
  });

  it('rejects a blank status — the thing that would render as an empty cell', () => {
    const doc = fixture();
    doc.repos[0].semgrep = { status: '', seconds: 0 };
    assert.ok(validateHeadToHead(doc).some((p) => /semgrep\.status/.test(p)));
  });

  it('rejects a missing eslintSecurity key (null is the explicit "not a JS/TS repo")', () => {
    const doc = fixture();
    delete doc.repos[1].eslintSecurity;
    assert.ok(validateHeadToHead(doc).some((p) => /eslintSecurity must be present/.test(p)));
  });

  it('refuses a SonarQube or CodeQL number nobody measured', () => {
    const doc = fixture();
    doc.tools.sonarqube = { status: 'ok', findings: 12 };
    const problems = validateHeadToHead(doc);
    assert.ok(problems.some((p) => /tools\.sonarqube\.status/.test(p)));
    assert.ok(problems.some((p) => /tools\.sonarqube\.reason/.test(p)));
  });

  it('requires a reason when a tool has no version', () => {
    const doc = fixture();
    doc.tools.semgrep = { version: null };
    assert.ok(validateHeadToHead(doc).some((p) => /tools\.semgrep: a null version needs a reason/.test(p)));
  });

  it('rejects duplicate repos and short shas', () => {
    const doc = fixture();
    doc.repos.push({ ...doc.repos[0], sha: 'abc123' });
    const problems = validateHeadToHead(doc);
    assert.ok(problems.some((p) => /duplicate repo/.test(p)));
    assert.ok(problems.some((p) => /sha must be a full 40-hex commit/.test(p)));
  });

  it('rejects an empty corpus', () => {
    assert.ok(validateHeadToHead(fixture({ repos: [] })).some((p) => /repos must not be empty/.test(p)));
    assert.deepStrictEqual(validateHeadToHead(null), ['document must be an object']);
  });

  // -------------------------------------------------------------------------
  // CodeQL — measured per repo now, but a document from before the adapter
  // existed (no per-repo codeql key, or the old document-level
  // {status:'not measured', reason} shape) must keep validating.
  // -------------------------------------------------------------------------

  it('accepts the versioned tools.codeql shape once the CLI has actually run', () => {
    const doc = fixture();
    doc.tools.codeql = { version: '2.27.0', command: 'codeql database create ...' };
    assert.deepStrictEqual(validateHeadToHead(doc), []);
  });

  it('rejects an empty tools.codeql entry (neither versioned nor the pre-adapter shape)', () => {
    const doc = fixture();
    doc.tools.codeql = {};
    assert.ok(validateHeadToHead(doc).some((p) => /tools\.codeql\.version must be a string or null/.test(p)));
  });

  it('rejects a versioned tools.codeql with a null version and no reason', () => {
    const doc = fixture();
    doc.tools.codeql = { version: null };
    assert.ok(validateHeadToHead(doc).some((p) => /tools\.codeql: a null version needs a reason/.test(p)));
  });

  it('rejects an ok codeql row missing its blocking-equivalent/total counts', () => {
    const doc = fixture();
    doc.repos[0].codeql = { status: 'ok', seconds: 1 };
    const problems = validateHeadToHead(doc);
    assert.ok(problems.some((p) => /codeql\.blocking must be an integer/.test(p)));
    assert.ok(problems.some((p) => /codeql\.total must be an integer/.test(p)));
  });

  it('rejects codeql blocking above total, the same rule gatetest gets', () => {
    const doc = fixture();
    doc.repos[0].codeql = { status: 'ok', blocking: 5, total: 2, seconds: 1 };
    assert.ok(validateHeadToHead(doc).some((p) => /codeql: blocking exceeds total/.test(p)));
  });

  it('rejects a not-measured codeql row without a reason — never a silent zero', () => {
    const doc = fixture();
    doc.repos[0].codeql = { status: 'not measured', seconds: 1 };
    assert.ok(validateHeadToHead(doc).some((p) => /codeql: a not-measured result needs a reason/.test(p)));
  });

  it('accepts codeql: null on a repo (explicitly skipped) and a repo with no codeql key at all', () => {
    const doc = fixture();
    doc.repos[0].codeql = null;
    delete doc.repos[1].codeql;
    assert.deepStrictEqual(validateHeadToHead(doc), []);
  });
});

// ---------------------------------------------------------------------------
// Run order, the --repos cut, the time box
// ---------------------------------------------------------------------------

describe('run order and limits', () => {
  const manifest = ['express', 'flask', 'fastify', 'got', 'hono', 'zod', 'django', 'rails', 'gin', 'laravel', 'NodeGoat'].map((name) => ({ name }));

  it('orderRepos puts the priority list first, then the manifest order', () => {
    const names = orderRepos(manifest).map((r) => r.name);
    assert.deepStrictEqual(names, ['express', 'django', 'rails', 'flask', 'fastify', 'zod', 'gin', 'laravel', 'got', 'hono', 'NodeGoat']);
  });

  it('orderRepos ignores priority names the manifest lacks and keeps every repo once', () => {
    const names = orderRepos(manifest, ['nope', 'gin', 'express']).map((r) => r.name);
    assert.strictEqual(names.length, manifest.length);
    assert.deepStrictEqual(names.slice(0, 2), ['gin', 'express']);
    assert.strictEqual(new Set(names).size, names.length);
  });

  it('limitRepos cuts after ordering; a missing or non-positive limit means all', () => {
    assert.deepStrictEqual(limitRepos(manifest, 3).map((r) => r.name), ['express', 'django', 'rails']);
    assert.strictEqual(limitRepos(manifest, null).length, manifest.length);
    assert.strictEqual(limitRepos(manifest, 0).length, manifest.length);
    assert.strictEqual(limitRepos(manifest, 99).length, manifest.length);
  });

  it('the time box is ten minutes per tool per repo', () => {
    assert.strictEqual(TOOL_TIMEOUT_MS, 10 * 60 * 1000);
  });

  it('elapsedSeconds reads an hrtime.bigint() start to one decimal', () => {
    const start = 1_000_000_000n;
    assert.strictEqual(elapsedSeconds(start, start + 41_250_000_000n), 41.3);
    assert.strictEqual(elapsedSeconds(start, start), 0);
    assert.ok(elapsedSeconds(process.hrtime.bigint()) < 1);
  });

  it('parseArgs understands the documented flags and rejects the rest', () => {
    const o = script.parseArgs(['--repos', '8', '--json', '--suite', 'quick', '--merge', '--no-eslint', '--timeout-minutes', '2']);
    assert.strictEqual(o.repos, 8);
    assert.strictEqual(o.json, true);
    assert.strictEqual(o.suite, 'quick');
    assert.strictEqual(o.merge, true);
    assert.strictEqual(o.eslint, false);
    assert.strictEqual(o.timeoutMs, 120000);
    assert.strictEqual(script.parseArgs([]).suite, 'full', 'the default suite is the one the corpus gate runs');
    assert.strictEqual(script.parseArgs([]).timeoutMs, TOOL_TIMEOUT_MS);
    assert.throws(() => script.parseArgs(['--repos', '0']), /positive integer/);
    assert.throws(() => script.parseArgs(['--bogus']), /unknown argument/);
  });
});

// ---------------------------------------------------------------------------
// The table — never a blank cell
// ---------------------------------------------------------------------------

describe('buildTable', () => {
  const table = buildTable(fixture());

  it('has one column per tool, bad columns included', () => {
    assert.deepStrictEqual(table.columns.map((c) => c.key), ['gatetest', 'semgrep', 'eslintSecurity', 'sonarqube', 'codeql']);
    assert.deepStrictEqual(table.columns.map((c) => c.version), ['1.61.1', null, null, null, null]);
  });

  it('never renders a blank cell, whatever the tool did', () => {
    for (const row of table.rows) {
      assert.strictEqual(row.cells.length, 5, `${row.name} has a cell per column`);
      for (const cell of row.cells) {
        assert.strictEqual(typeof cell.text, 'string');
        assert.ok(cell.text.trim().length > 0, `${row.name}: blank cell`);
        assert.ok(cell.kind, `${row.name}: cell has a kind`);
      }
    }
  });

  it('says what happened in the non-ok cells', () => {
    const [express, django, gin] = table.rows;
    assert.match(express.cells[0].text, /^0 blocking \/ 13 findings$/);
    assert.strictEqual(express.cells[0].detail, '41.2 s');
    assert.strictEqual(express.cells[0].kind, 'clean');
    assert.strictEqual(express.cells[1].text, 'tool unavailable on this runner');
    assert.match(express.cells[2].text, /^timed out after 600\.0 s$/);
    assert.match(django.cells[0].text, /^timed out after 600\.0 s$/);
    assert.match(django.cells[1].text, /^3 error \/ 40 warning \/ 2 info$/);
    assert.match(django.cells[2].text, /^not run — not a JavaScript\/TypeScript repository$/);
    assert.match(gin.cells[0].text, /^failed \(exit 3\)$/);
    assert.match(gin.cells[1].text, /^failed \(exit 2\)/);
  });

  it('renders SonarQube as not measured for every repo, with the document reason', () => {
    for (const row of table.rows) {
      assert.match(row.cells[3].text, /^not measured — needs a server$/);
    }
  });

  it('renders CodeQL per repo: measured when the adapter ran, not-measured with the reason when it could not, and generically not-measured for a row from before the column existed', () => {
    const [express, django, gin] = table.rows;
    assert.match(express.cells[4].text, /^2 blocking-equivalent \/ 9 results$/);
    assert.strictEqual(express.cells[4].detail, '88.4 s');
    assert.strictEqual(express.cells[4].kind, 'measured');
    assert.match(django.cells[4].text, /^not measured — codeql database create failed \(exit 1\)/);
    assert.strictEqual(django.cells[4].kind, 'not-measured');
    assert.strictEqual(gin.cells[4].text, STATUS.notMeasured, 'a row with no codeql key at all still says something, never blank');
    assert.strictEqual(gin.cells[4].kind, 'not-measured');
  });

  it('survives a document with nothing in it rather than throwing on the page', () => {
    const empty = buildTable({});
    assert.strictEqual(empty.rows.length, 0);
    assert.strictEqual(empty.columns.length, 5);
    const nulls = buildTable({ repos: [{ name: 'x', url: 'u', sha: SHA, gatetest: null, semgrep: undefined }] });
    for (const cell of nulls.rows[0].cells) assert.ok(cell.text.trim().length > 0, 'null tools still say something');
    assert.strictEqual(nulls.rows[0].language, 'unknown');
  });
});

// ---------------------------------------------------------------------------
// The script's own helpers
// ---------------------------------------------------------------------------

describe('scripts/head-to-head.js helpers', () => {
  it('detectLanguage counts by extension, skipping node_modules and .git', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gt-h2h-lang-'));
    try {
      fs.mkdirSync(path.join(dir, 'src'));
      fs.mkdirSync(path.join(dir, 'node_modules', 'x'), { recursive: true });
      fs.writeFileSync(path.join(dir, 'src', 'a.py'), '');
      fs.writeFileSync(path.join(dir, 'src', 'b.py'), '');
      fs.writeFileSync(path.join(dir, 'c.js'), '');
      for (let i = 0; i < 5; i += 1) fs.writeFileSync(path.join(dir, 'node_modules', 'x', `${i}.js`), '');
      const { language, fileCounts } = script.detectLanguage(dir);
      assert.strictEqual(language, 'Python');
      assert.deepStrictEqual(fileCounts, { Python: 2, JavaScript: 1 });
      assert.strictEqual(script.detectLanguage(path.join(dir, 'node_modules', 'x', 'nope')).language, 'unknown');
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('countSemgrep buckets by the labels Semgrep uses and keeps anything else honest', () => {
    const counts = script.countSemgrep([
      { extra: { severity: 'ERROR' } }, { extra: { severity: 'error' } },
      { extra: { severity: 'WARNING' } }, { extra: { severity: 'INFO' } },
      { extra: { severity: 'HIGH' } }, { extra: {} },
    ]);
    assert.deepStrictEqual(counts, { error: 2, warning: 1, info: 1, other: 2, otherSeverities: ['(none)', 'HIGH'] });
  });

  it('the throwaway ESLint config runs only eslint-plugin-security, from the temp dir', () => {
    const cfg = script.eslintConfig(path.join(os.tmpdir(), 'gt-h2h-x', 'eslint-security'));
    assert.match(cfg, /security\.configs\.recommended\.rules/);
    assert.match(cfg, /import security from "file:\/\/\//);
    assert.match(cfg, /import tsParser from "file:\/\/\//);
    assert.doesNotMatch(cfg, /js\.configs\.recommended/, 'no general lint rules — the column is security findings');
    assert.ok(!fs.existsSync(path.join(ROOT, 'node_modules', 'eslint-plugin-security')), 'the plugin is never installed in this repository');
  });

  it('this repository gains no dependency from the comparison', () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    const all = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}), ...(pkg.optionalDependencies || {}) };
    for (const name of ['eslint-plugin-security', '@typescript-eslint/parser', 'semgrep', '@semgrep/semgrep']) {
      assert.ok(!(name in all), `${name} must not be a dependency of this repository`);
    }
  });
});

// ---------------------------------------------------------------------------
// The CodeQL adapter — offline: no CLI, no network, no real clone needed
// ---------------------------------------------------------------------------

describe('scripts/head-to-head.js CodeQL adapter', () => {
  /** A minimal CodeQL SARIF document with one run. */
  function sarifFixture(results, rules = []) {
    return { runs: [{ tool: { driver: { name: 'CodeQL', rules } }, results }] };
  }

  it('counts two errors and one note as documented: level "error" is blocking-equivalent, "note" is not', () => {
    const sarif = sarifFixture([
      { level: 'error', ruleId: 'js/sql-injection' },
      { level: 'error', ruleId: 'js/path-injection' },
      { level: 'note', ruleId: 'js/useless-assignment' },
    ]);
    assert.deepStrictEqual(script.countCodeqlSarif(sarif), { blocking: 2, total: 3 });
  });

  it('a security-severity >= 7.0 on a non-error result still counts as blocking-equivalent; below 7.0 does not', () => {
    const sarif = sarifFixture([
      { level: 'warning', ruleId: 'a', properties: { 'security-severity': '7.0' } },
      { level: 'warning', ruleId: 'b', properties: { 'security-severity': '6.9' } },
    ]);
    assert.deepStrictEqual(script.countCodeqlSarif(sarif), { blocking: 1, total: 2 });
  });

  it('a rule-level problem.severity of "error" counts as blocking-equivalent even when the result level does not', () => {
    const sarif = sarifFixture(
      [{ level: 'warning', ruleId: 'c', ruleIndex: 0 }],
      [{ id: 'c', properties: { 'problem.severity': 'error' } }],
    );
    assert.deepStrictEqual(script.countCodeqlSarif(sarif), { blocking: 1, total: 1 });
  });

  it('an empty or missing SARIF run counts nothing, never throwing', () => {
    assert.deepStrictEqual(script.countCodeqlSarif({}), { blocking: 0, total: 0 });
    assert.deepStrictEqual(script.countCodeqlSarif({ runs: [] }), { blocking: 0, total: 0 });
    assert.deepStrictEqual(script.countCodeqlSarif(null), { blocking: 0, total: 0 });
  });

  it('codeql temp paths (db + sarif) are siblings of the clone, never inside it', () => {
    const dir = path.join(os.tmpdir(), 'gt-h2h-xxxx', 'express');
    const paths = script.codeqlPaths(dir);
    assert.ok(!paths.db.startsWith(`${dir}${path.sep}`), 'the database must not live inside the clone');
    assert.ok(!paths.sarif.startsWith(`${dir}${path.sep}`), 'the SARIF output must not live inside the clone');
    assert.strictEqual(path.dirname(paths.db), path.dirname(dir), 'both are siblings of the clone in the script\'s tmp dir');
  });

  it('an unsupported language is not-measured without attempting a CLI call, never a zero', () => {
    const row = script.runCodeql({ bin: 'codeql' }, '/does/not/matter', 'Rust', 5000);
    assert.strictEqual(row.status, 'not measured');
    assert.match(row.reason, /Rust/);
    assert.strictEqual(row.blocking, undefined);
    assert.strictEqual(row.seconds, 0);
  });

  it('a CodeQL run that cannot spawn the CLI is not-measured with the reason, never a zero', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'gt-h2h-codeql-'));
    try {
      const dir = path.join(tmp, 'repo');
      fs.mkdirSync(dir);
      const row = script.runCodeql({ bin: 'gt-h2h-nonexistent-codeql-binary-xyz' }, dir, 'JavaScript', 5000);
      assert.strictEqual(row.status, 'not measured');
      assert.strictEqual(row.blocking, undefined, 'a failed run never reports a blocking count');
      assert.match(row.reason, /database create/);
      assert.strictEqual(row.language, 'JavaScript');
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });

  it('findCodeql looks at CODEQL_HOME before PATH and returns null rather than throwing when neither has one', () => {
    assert.strictEqual(typeof script.findCodeql, 'function');
    const saved = process.env.CODEQL_HOME;
    delete process.env.CODEQL_HOME;
    try {
      // This sandbox has no CodeQL CLI installed; the important thing is
      // that a missing tool is `null`, never a thrown exception.
      assert.doesNotThrow(() => script.findCodeql());
    } finally {
      if (saved === undefined) delete process.env.CODEQL_HOME; else process.env.CODEQL_HOME = saved;
    }
  });
});

// ---------------------------------------------------------------------------
// The committed file
// ---------------------------------------------------------------------------

describe('website/app/data/head-to-head.json — generated, valid, pinned to the corpus', () => {
  const doc = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));
  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
  const corpus = Object.fromEntries(manifest.repos.map((r) => [r.name, r]));

  it('validates', () => {
    assert.deepStrictEqual(validateHeadToHead(doc), []);
  });

  it('names the manifest size and never claims more repos than the corpus has', () => {
    assert.strictEqual(doc.corpusSize, manifest.repos.length);
    assert.ok(doc.repos.length <= manifest.repos.length);
  });

  it('every repo is a corpus repo at the commit the corpus pins', () => {
    for (const r of doc.repos) {
      assert.ok(corpus[r.name], `${r.name} is not in reliability-corpus/real-world.json`);
      assert.strictEqual(r.sha, corpus[r.name].sha, `${r.name}: the table must be measured on the pinned commit`);
      assert.strictEqual(r.url, corpus[r.name].url);
    }
  });

  it('SonarQube is not measured until it is measured for real', () => {
    assert.strictEqual(doc.tools.sonarqube.status, STATUS.notMeasured);
    assert.ok(typeof doc.tools.sonarqube.reason === 'string' && doc.tools.sonarqube.reason.length > 0);
  });

  it('CodeQL is either measured for real (version string) or says why not', () => {
    // Mirrors validate(): the adapter runs CodeQL on the runner now, so a
    // measured document carries a version string; one produced without the
    // CLI carries null + reason; the pre-adapter shape stays valid.
    const v = doc.tools.codeql;
    if (v.status === STATUS.notMeasured) {
      assert.ok(typeof v.reason === 'string' && v.reason.length > 0, 'not measured needs a reason');
    } else {
      assert.ok(v.version === null || typeof v.version === 'string', 'version must be a string or null');
      if (v.version === null) assert.ok(typeof v.reason === 'string', 'a null version needs a reason');
    }
  });

  it('renders without a blank cell', () => {
    for (const row of buildTable(doc).rows) {
      for (const cell of row.cells) assert.ok(cell.text.trim().length > 0, `${row.name}: blank cell`);
    }
  });

  it('names no AI vendor or model', () => {
    assert.doesNotMatch(JSON.stringify(doc), /\b(claude|anthropic|fable|sonnet|opus|haiku|openai|gpt-?\d)\b/i);
  });
});

// ---------------------------------------------------------------------------
// The page and the workflow
// ---------------------------------------------------------------------------

describe('/precision — the head-to-head section reads the file through the shared module', () => {
  const src = fs.readFileSync(PAGE_PATH, 'utf8');

  it('imports head-to-head.json and buildTable', () => {
    assert.match(src, /from "\.\.\/data\/head-to-head\.json"/);
    assert.match(src, /from "\.\.\/lib\/head-to-head"/);
    assert.match(src, /buildTable\(/);
  });

  it('has the section and its honest framing', () => {
    assert.match(src, /Head to head/);
    assert.match(src, /not comparable one-to-one/);
    assert.match(src, /cell\.text/, 'cells render the builder text — that is what cannot be blank');
  });

  it('types no measured count into the JSX', () => {
    const doc = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));
    for (const r of doc.repos) {
      if (r.gatetest && typeof r.gatetest.blocking === 'number') {
        assert.ok(!new RegExp(`>\\s*${r.gatetest.blocking} blocking`).test(src), `page hardcodes ${r.name}'s blocking count`);
      }
    }
  });
});

describe('.github/workflows/head-to-head.yml', () => {
  const yml = fs.readFileSync(WORKFLOW_PATH, 'utf8');

  it('runs weekly and on demand, on ubuntu, with Semgrep from pip', () => {
    assert.match(yml, /schedule:\s*\r?\n\s*- cron:/);
    assert.match(yml, /workflow_dispatch:/);
    assert.match(yml, /runs-on: ubuntu-latest/);
    assert.match(yml, /pip install (--upgrade )?semgrep/);
  });

  it('regenerates the committed file with the script and ships it on a rolling PR', () => {
    assert.match(yml, /node scripts\/head-to-head\.js/);
    assert.match(yml, /website\/app\/data\/head-to-head\.json/);
    assert.match(yml, /gh pr create/);
    // The comments may explain the manifest; the shipped file list may not
    // carry it, and the ratchet belongs to the nightly alone.
    const shipped = yml.match(/GENERATED="([^"]*)"/);
    assert.ok(shipped, 'the PR step names the generated files it ships');
    assert.strictEqual(shipped[1], 'website/app/data/head-to-head.json', 'only the table rides this PR — never the ceilings');
    const commands = yml.split(/\r?\n/).filter((l) => !/^\s*#/.test(l)).join('\n');
    assert.doesNotMatch(commands, /--ratchet/, 'the comparison never ratchets a ceiling');
    assert.doesNotMatch(commands, /real-world\.json/, 'no command touches the manifest');
  });

  it('installs a pinned, checksum-verified CodeQL CLI release before Measure, and exports CODEQL_HOME/PATH', () => {
    assert.match(yml, /Install CodeQL CLI/);
    const installIdx = yml.indexOf('Install CodeQL CLI');
    const measureIdx = yml.search(/- name: Measure\r?\n/);
    assert.ok(installIdx > -1 && measureIdx > installIdx, 'the CodeQL install step must run before Measure');
    const installStep = yml.slice(installIdx, measureIdx);
    assert.match(installStep, /codeql-bundle-v[\d.]+/, 'pins an exact release tag, never a mutable "latest"');
    assert.match(installStep, /codeql-bundle-linux64\.tar\.gz/);
    assert.match(installStep, /sha256sum -c/, 'verifies the download against the release\'s own checksum');
    assert.match(installStep, /CODEQL_HOME/);
    assert.match(installStep, /GITHUB_ENV/);
    assert.match(installStep, /GITHUB_PATH/);
    assert.match(installStep, /codeql version|codeql"\s*version/, 'prints the installed version');
  });

  it('never swallows a step failure with `|| true`, and the CodeQL install step never interpolates event data', () => {
    const commands = yml.split(/\r?\n/).filter((l) => !/^\s*#/.test(l)).join('\n');
    assert.doesNotMatch(commands, /\|\|\s*true\b/, 'a failure must be visible, never swallowed with `|| true`');
    const installStep = yml.slice(yml.indexOf('Install CodeQL CLI'), yml.indexOf('name: Install all workspaces'));
    assert.doesNotMatch(installStep, /\$\{\{\s*github\.event/, 'event data must flow through env: (like LIMIT does), never be interpolated directly into the script');
    // The only untrusted input this workflow takes (workflow_dispatch's
    // `repos`) already flows through env: as LIMIT — the pattern this step
    // must also follow for anything it ever reads from the event.
    assert.match(yml, /LIMIT: \$\{\{ github\.event\.inputs\.repos \}\}/);
  });
});
