const { describe, it } = require('node:test');
const assert = require('node:assert');

const {
  HostBridge,
  NotImplemented,
  CANONICAL_COMMIT_STATES,
  registerBridge,
  createBridge,
  listBridges,
} = require('../src/core/host-bridge');

describe('HostBridge abstract surface', () => {
  it('exposes canonical commit-status vocabulary', () => {
    assert.deepStrictEqual(
      CANONICAL_COMMIT_STATES,
      ['pending', 'success', 'failure', 'error'],
    );
  });

  it('throws NotImplemented for every abstract primitive', async () => {
    const bridge = new HostBridge();
    const primitives = [
      ['healthCheck', []],
      ['verifyAuth', []],
      ['accessRepo', ['o', 'r', '/tmp']],
      ['cloneRepo', ['o', 'r', '/tmp']],
      ['pull', ['/tmp']],
      ['push', ['/tmp']],
      ['getDefaultBranch', ['o', 'r']],
      ['createBranch', ['o', 'r', 'feat', 'sha']],
      ['createPullRequest', ['o', 'r', {}]],
      ['getPullRequest', ['o', 'r', 1]],
      ['updatePullRequest', ['o', 'r', 1, {}]],
      ['addPrComment', ['o', 'r', 1, 'body']],
      ['listPrComments', ['o', 'r', 1]],
      ['createCommit', ['o', 'r', {}]],
      ['getCommit', ['o', 'r', 'sha']],
      ['listCommits', ['o', 'r']],
      ['setCommitStatus', ['o', 'r', 'sha', 'success', 'desc']],
      ['getCombinedStatus', ['o', 'r', 'ref']],
    ];
    for (const [method, args] of primitives) {
      await assert.rejects(
        () => bridge[method](...args),
        (err) => err.name === 'NotImplemented' && err.method === method,
        `${method} must throw NotImplemented`,
      );
    }
  });

  it('throws NotImplemented for synchronous primitives', () => {
    const bridge = new HostBridge();
    assert.throws(() => bridge.getAccessStatus(), { name: 'NotImplemented' });
    assert.throws(() => bridge.resetCircuitBreaker(), { name: 'NotImplemented' });
    assert.throws(() => bridge.createWebhookServer({}), { name: 'NotImplemented' });
  });

  it('reports its host name via static and instance getters', () => {
    class MyBridge extends HostBridge {
      static get hostName() { return 'myhost'; }
    }
    assert.strictEqual(MyBridge.hostName, 'myhost');
    assert.strictEqual(new MyBridge().hostName, 'myhost');
  });

  it('defaults projectRoot to process.cwd() when not provided', () => {
    const bridge = new HostBridge();
    assert.strictEqual(bridge.projectRoot, process.cwd());
  });

  it('respects explicit projectRoot option', () => {
    const bridge = new HostBridge({ projectRoot: '/tmp/foo' });
    assert.strictEqual(bridge.projectRoot, '/tmp/foo');
  });
});

describe('HostBridge._validateCommitState', () => {
  const bridge = new HostBridge();

  it('accepts canonical states', () => {
    for (const state of CANONICAL_COMMIT_STATES) {
      assert.doesNotThrow(() => bridge._validateCommitState(state));
    }
  });

  it('rejects unknown states', () => {
    assert.throws(() => bridge._validateCommitState('succeeded'), /Invalid commit status state/);
    assert.throws(() => bridge._validateCommitState(''), /Invalid commit status state/);
    assert.throws(() => bridge._validateCommitState(null), /Invalid commit status state/);
  });
});

describe('HostBridge._formatGateResultMarkdown', () => {
  const bridge = new HostBridge();

  it('renders PASSED markdown with totals table', () => {
    const md = bridge._formatGateResultMarkdown({
      status: 'passed',
      totalChecks: 5,
      passed: 5,
      failed: 0,
      skipped: 0,
      duration: 1234,
    });
    assert.match(md, /GateTest Quality Gate — PASSED/);
    assert.match(md, /:white_check_mark:/);
    assert.match(md, /\| \*\*Total Checks\*\* \| 5 \|/);
    assert.match(md, /\| \*\*Duration\*\* \| 1\.2s \|/);
    assert.match(md, /Generated by <b>GateTest v\d+\.\d+\.\d+<\/b>/);
  });

  it('renders FAILED markdown with failure details block', () => {
    const md = bridge._formatGateResultMarkdown({
      status: 'failed',
      totalChecks: 3,
      passed: 1,
      failed: 2,
      skipped: 0,
      duration: 500,
      failures: [
        {
          module: 'lint',
          check: 'no-unused-vars',
          expected: 'no unused',
          actual: 'x unused',
          file: 'src/a.js',
          line: 3,
          message: 'unused variable',
          suggestion: 'remove it',
        },
      ],
    });
    assert.match(md, /GateTest Quality Gate — FAILED/);
    assert.match(md, /:x:/);
    assert.match(md, /500ms/);
    assert.match(md, /### Failures/);
    assert.match(md, /<summary><b>lint<\/b>: no-unused-vars<\/summary>/);
    assert.match(md, /\*\*File:\*\* `src\/a\.js`:3/);
    assert.match(md, /\*\*Suggested fix:\*\* remove it/);
  });

  it('renders module results table when provided', () => {
    const md = bridge._formatGateResultMarkdown({
      status: 'passed',
      totalChecks: 2,
      passed: 2,
      failed: 0,
      skipped: 0,
      duration: 100,
      modules: [
        { name: 'lint', status: 'passed', checks: 2, duration: 50 },
        { name: 'sec', status: 'skipped', duration: 10 },
      ],
    });
    assert.match(md, /### Module Results/);
    assert.match(md, /\| :white_check_mark: lint \| passed \| 2 \| 50ms \|/);
    assert.match(md, /\| :fast_forward: sec \| skipped \| - \| 10ms \|/);
  });
});

describe('HostBridge.reportResults', () => {
  class SpyBridge extends HostBridge {
    static get hostName() { return 'spy'; }
    constructor() {
      super();
      this.calls = { setCommitStatus: null, addPrComment: null };
    }
    async setCommitStatus(owner, repo, sha, state, description) {
      this.calls.setCommitStatus = { owner, repo, sha, state, description };
      return { ok: true, state };
    }
    async addPrComment(owner, repo, prNumber, body) {
      this.calls.addPrComment = { owner, repo, prNumber, body };
      return { ok: true };
    }
  }

  it('derives success state and description from a passed summary', async () => {
    const bridge = new SpyBridge();
    const res = await bridge.reportResults('o', 'r', 42, 'abc', {
      status: 'passed',
      totalChecks: 3,
      passed: 3,
      failed: 0,
      skipped: 0,
      duration: 100,
    });
    assert.strictEqual(bridge.calls.setCommitStatus.state, 'success');
    assert.strictEqual(bridge.calls.setCommitStatus.description, 'All 3 checks passed');
    assert.match(bridge.calls.addPrComment.body, /PASSED/);
    assert.ok(res.status.ok);
    assert.ok(res.comment.ok);
  });

  it('derives failure state and description from a failed summary', async () => {
    const bridge = new SpyBridge();
    await bridge.reportResults('o', 'r', 42, 'abc', {
      status: 'failed',
      totalChecks: 5,
      passed: 3,
      failed: 2,
      skipped: 0,
      duration: 100,
    });
    assert.strictEqual(bridge.calls.setCommitStatus.state, 'failure');
    assert.strictEqual(bridge.calls.setCommitStatus.description, '2 of 5 checks failed');
    assert.match(bridge.calls.addPrComment.body, /FAILED/);
  });
});

describe('HostBridge registry', () => {
  it('roundtrips a registered bridge via createBridge', () => {
    class FakeBridge extends HostBridge {
      static get hostName() { return 'fakehost-roundtrip'; }
    }
    registerBridge(FakeBridge.hostName, FakeBridge);
    assert.ok(listBridges().includes('fakehost-roundtrip'));

    const instance = createBridge('fakehost-roundtrip', { projectRoot: '/x' });
    assert.ok(instance instanceof FakeBridge);
    assert.ok(instance instanceof HostBridge);
    assert.strictEqual(instance.projectRoot, '/x');
    assert.strictEqual(instance.hostName, 'fakehost-roundtrip');
  });

  it('is case-insensitive on host names', () => {
    class CasedBridge extends HostBridge {
      static get hostName() { return 'CaseTest'; }
    }
    registerBridge('CaseTest', CasedBridge);
    assert.ok(createBridge('casetest') instanceof CasedBridge);
    assert.ok(createBridge('CASETEST') instanceof CasedBridge);
  });

  it('throws with a helpful message when no bridge is registered for a host', () => {
    assert.throws(
      () => createBridge('nonexistent-host-xyz'),
      /No bridge registered for host "nonexistent-host-xyz"/,
    );
  });

  it('throws when createBridge is called without a host name', () => {
    assert.throws(() => createBridge(), /requires a hostName/);
    assert.throws(() => createBridge(''), /requires a hostName/);
  });

  it('rejects invalid registerBridge arguments', () => {
    assert.throws(() => registerBridge('', class {}), /non-empty hostName/);
    assert.throws(() => registerBridge(null, class {}), /non-empty hostName/);
    assert.throws(() => registerBridge('x', 'not-a-class'), /requires a class/);
  });

  it('auto-registers the GitHub bridge when github-bridge is imported', () => {
    // github-bridge registers itself on require.
    require('../src/core/github-bridge');
    assert.ok(listBridges().includes('github'));
    const bridge = createBridge('github');
    assert.strictEqual(bridge.hostName, 'github');
    assert.ok(bridge instanceof HostBridge);
  });
});

describe('NotImplemented error', () => {
  it('includes the method name and host name in the message', () => {
    const err = new NotImplemented('foo', 'github');
    assert.strictEqual(err.name, 'NotImplemented');
    assert.strictEqual(err.method, 'foo');
    assert.match(err.message, /foo\(\) is not implemented/);
    assert.match(err.message, /for host "github"/);
  });

  it('omits the host suffix when no host is provided', () => {
    const err = new NotImplemented('foo');
    assert.match(err.message, /foo\(\) is not implemented\./);
    assert.doesNotMatch(err.message, /for host/);
  });
});

// Regression: every GateTest PR comment must start with a signature
// HTML-comment marker. PR-comment posters (github-bridge, github-callback)
// rely on the marker to find prior comments and PATCH them in place
// rather than POSTing a duplicate on every push (Known Issue #23).
describe('HostBridge — PR comment signature marker', () => {
  const { HostBridge, GATETEST_PR_COMMENT_MARKER } = require('../src/core/host-bridge');

  it('exports the canonical marker string', () => {
    assert.strictEqual(typeof GATETEST_PR_COMMENT_MARKER, 'string');
    assert.ok(GATETEST_PR_COMMENT_MARKER.length > 0);
    assert.ok(GATETEST_PR_COMMENT_MARKER.startsWith('<!--'),
      'marker must be an HTML comment so it renders invisibly in GitHub UI');
    assert.ok(GATETEST_PR_COMMENT_MARKER.includes('gatetest-bot'),
      'marker must identify the bot owner unambiguously');
  });

  it('formatPullRequestComment output starts with the marker', () => {
    class TestBridge extends HostBridge {
      constructor() { super({ token: 'x' }); }
    }
    const b = new TestBridge();
    const md = b._formatGateResultMarkdown({
      status: 'passed',
      totalChecks: 5,
      passed: 5,
      failed: 0,
      skipped: 0,
      duration: 1234,
      modules: [],
    });
    assert.ok(md.startsWith(GATETEST_PR_COMMENT_MARKER),
      `expected output to start with marker. got: ${md.slice(0, 80)}`);
  });
});
