import buildInfo from "@/app/data/build-info.json";
import { SUPPORT_EMAIL } from "@/app/lib/site-url";

// The Fifty, move 38: every comparison page carries the date it was last
// changed and the engine version it was built against — both generated by
// scripts/generate-build-info.js at build time, never typed. A comparison
// claim with no date becomes the competitor's best asset the day it goes
// stale; one with a date is a claim the reader can weigh.
type PageDates = Record<string, string>;
const pageUpdated: PageDates = (buildInfo as { pageUpdated?: PageDates }).pageUpdated || {};

export default function ComparisonReviewed({ slug }: { slug: string }) {
  const date = pageUpdated[slug];
  const version = (buildInfo as { version?: string }).version;
  return (
    <section
      aria-label="How current this comparison is"
      className="max-w-5xl mx-auto px-6 mt-14 text-xs text-muted leading-relaxed"
    >
      <p>
        {date ? (
          <>
            This comparison was last updated on <time dateTime={date}>{date}</time>
            {version && version !== "dev" ? <> against GateTest v{version}</> : null}.
          </>
        ) : version && version !== "dev" ? (
          <>This comparison is published against GateTest v{version}.</>
        ) : (
          <>This comparison is dated at build time.</>
        )}{" "}
        Other tools change; if a claim here is out of date, tell us at{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`} className="underline hover:text-foreground">
          {SUPPORT_EMAIL}
        </a>{" "}
        and we will correct it.
      </p>
    </section>
  );
}
