"use client";

import { useState } from "react";
import { type Finding, type ScanResult, type Severity } from "./url-scan-flow-types";

export function formatFindingsForClaude(result: ScanResult): string {
  const lines: string[] = [];
  lines.push(`# GateTest scan report — paste-ready for Claude Code`);
  lines.push("");
  lines.push(`**Site scanned:** ${result.targetUrl}`);
  lines.push(`**Health Score:** ${result.healthScore.score} / 100 (Grade ${result.healthScore.grade})`);
  lines.push(`**Summary:** ${result.healthScore.summary}`);
  lines.push("");
  lines.push(`## Task for Claude`);
  lines.push(`Investigate the codebase that powers \`${result.targetUrl}\` and fix the issues below. Where the source of an issue isn't obvious, search for the relevant file. Group fixes by root cause where possible — many of these findings collapse to a single configuration change.`);
  lines.push("");

  const bySev: Record<Severity, Finding[]> = { error: [], warning: [], info: [] };
  for (const f of result.findings) {
    bySev[f.severity].push(f);
  }

  for (const sev of ["error", "warning", "info"] as Severity[]) {
    const items = bySev[sev];
    if (items.length === 0) continue;
    const label = sev === "error" ? "🔴 Errors" : sev === "warning" ? "🟡 Warnings" : "⚪ Info";
    lines.push(`## ${label} (${items.length})`);
    lines.push("");
    items.forEach((f, i) => {
      const flag = f.highSignal ? " 🔥 HIGH-SIGNAL" : "";
      const count = f.instanceCount && f.instanceCount > 1 ? ` × ${f.instanceCount}` : "";
      lines.push(`### ${i + 1}. ${f.title}${flag}${count}`);
      lines.push(`- **Module:** \`${f.module}\``);
      lines.push(`- **Rule:** \`${f.ruleKey}\``);
      if (f.body) {
        const body = f.body.split("\n").map((l) => `  ${l}`).join("\n");
        lines.push("");
        lines.push(body.trimEnd());
      }
      lines.push("");
    });
  }

  lines.push(`---`);
  lines.push(`_Generated by GateTest — https://gatetest.ai_`);
  return lines.join("\n");
}

export function CopyForClaudeButton({ result }: { result: ScanResult }) {
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState(false);

  async function copy() {
    const text = formatFindingsForClaude(result);
    try {
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(text);
      } else {
        const ta = document.createElement("textarea");
        ta.value = text;
        ta.style.position = "fixed";
        ta.style.left = "-9999px";
        document.body.appendChild(ta);
        ta.select();
        document.execCommand("copy");
        document.body.removeChild(ta);
      }
      setCopied(true);
      setError(false);
      setTimeout(() => setCopied(false), 2400);
    } catch {
      setError(true);
      setTimeout(() => setError(false), 2400);
    }
  }

  return (
    <div className="rounded-2xl border border-accent/20 bg-accent/5 p-5 sm:p-6 flex flex-col sm:flex-row items-start sm:items-center gap-4">
      <div className="flex-1">
        <p className="font-semibold text-foreground leading-tight">
          Hand this report to Claude
        </p>
        <p className="text-sm text-muted mt-1 leading-relaxed">
          Copy the findings as a structured prompt ready to paste into any Claude Code or chat session.
          Claude will know the URL, the issues, the severity, and what to fix.
        </p>
      </div>
      <button
        type="button"
        onClick={copy}
        className={`shrink-0 inline-flex items-center gap-2 px-5 py-3 rounded-xl font-semibold transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-accent/40 ${
          copied
            ? "bg-emerald-600 text-white"
            : error
            ? "bg-rose-600 text-white"
            : "bg-accent text-white hover:bg-accent-hover"
        }`}
        aria-live="polite"
      >
        {copied ? (
          <>
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
            </svg>
            Copied
          </>
        ) : error ? (
          <>Copy failed — try again</>
        ) : (
          <>
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1m-6-13h6a2 2 0 012 2v6a2 2 0 01-2 2h-6a2 2 0 01-2-2V7a2 2 0 012-2z" />
            </svg>
            Copy findings for Claude
          </>
        )}
      </button>
    </div>
  );
}
