"use client";

export interface GuidanceItem {
  module: string;
  detail: string;
  title: string;
  why: string;
  steps: string[];
  commands?: string[];
}

// Step-by-step manual fix guide generated by /api/scan/guidance for the
// findings the auto-fixer can't act on.
export function GuidancePanel({ guidance, onClose }: { guidance: GuidanceItem[]; onClose: () => void }) {
  return (
    <div className="rounded-xl bg-white border border-gray-200 shadow-sm p-5 mt-4 border-l-4 border-l-accent">
      <div className="flex items-center justify-between mb-3">
        <h3 className="font-bold">Step-by-step fix guide ({guidance.length} issues)</h3>
        <button
          onClick={onClose}
          className="text-gray-500 hover:text-gray-900 text-lg px-2"
          aria-label="Close guide"
        >
          &times;
        </button>
      </div>
      <div className="space-y-4">
        {guidance.map((g, i) => (
          <div key={i} className="rounded-lg border border-gray-200 p-4 bg-gray-50">
            <div className="flex items-baseline gap-2 mb-1">
              <span className="text-xs font-mono text-accent font-bold">{g.module}</span>
              <h4 className="font-semibold text-sm">{g.title}</h4>
            </div>
            <p className="text-xs text-gray-500 mb-3">{g.why}</p>
            <ol className="text-sm space-y-1 list-decimal list-inside">
              {g.steps.map((s, j) => (
                <li key={j} className="text-gray-800">{s}</li>
              ))}
            </ol>
            {g.commands && g.commands.length > 0 && (
              <div className="mt-3 space-y-1">
                {g.commands.map((cmd, j) => (
                  <pre key={j} className="bg-gray-900 text-emerald-400 text-xs font-mono p-2 rounded overflow-x-auto">{cmd}</pre>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
