"use client";

import { useState } from "react";

// One ready-to-paste config fix generated by /api/scan/server-fix.
// Shared with the Forensic tab's snippet renderer.
export interface ServerFix {
  platform: string;
  title: string;
  code: string;
  instructions: string;
}

// The "Server Scan" tab — scan a live URL for SSL, security headers, DNS,
// and performance, then generate ready-to-paste config fixes.
export function ServerScanTab() {
  const [url, setUrl] = useState("");
  const [scanning, setScanning] = useState(false);
  const [result, setResult] = useState<Record<string, unknown> | null>(null);
  const [error, setError] = useState("");
  const [generatingFixes, setGeneratingFixes] = useState(false);
  const [fixes, setFixes] = useState<Record<string, ServerFix[]> | null>(null);
  const [copiedCode, setCopiedCode] = useState<string | null>(null);

  async function runServerScan() {
    if (!url) { setError("Enter a URL"); return; }
    setScanning(true); setResult(null); setError(""); setFixes(null);
    try {
      const res = await fetch("/api/scan/server", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url }),
      });
      const data = await res.json();
      if (!res.ok) { setError(data.error || "Scan failed"); return; }
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Scan failed");
    } finally { setScanning(false); }
  }

  async function generateFixes() {
    if (!result) return;
    setGeneratingFixes(true);
    try {
      const res = await fetch("/api/scan/server-fix", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ hostname: result.hostname, modules: result.modules }),
      });
      const data = await res.json();
      setFixes(data.fixes || {});
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not generate fixes");
    } finally { setGeneratingFixes(false); }
  }

  function copyCode(code: string, id: string) {
    navigator.clipboard.writeText(code);
    setCopiedCode(id);
    setTimeout(() => setCopiedCode(null), 1500);
  }

  const modules = (result?.modules as Array<Record<string, unknown>>) || [];
  const totalIssues = (result?.totalIssues as number) || 0;

  return (
    <>
      <div className="rounded-xl bg-white border border-gray-200 shadow-sm p-6 mb-8">
        <p className="text-sm text-gray-500 mb-3">Scan a live URL for SSL, security headers, DNS, and performance.</p>
        <div className="flex gap-3">
          <input
            type="url"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter") runServerScan(); }}
            placeholder="https://example.com"
            className="flex-1 px-4 py-3 rounded-xl border border-gray-300 bg-white text-gray-900 placeholder:text-gray-400 focus:border-emerald-500 focus:outline-none focus:ring-1 focus:ring-emerald-500/30 text-sm"
          />
          <button onClick={runServerScan} disabled={scanning} className="btn-primary px-6 py-3 text-sm disabled:opacity-50">
            {scanning ? "Scanning..." : "Scan Server"}
          </button>
        </div>
        {error && <p className="text-danger text-sm mt-3">{error}</p>}
      </div>

      {scanning && (
        <div className="rounded-xl bg-white border border-gray-200 shadow-sm p-8 text-center">
          <div className="w-8 h-8 border-2 border-accent border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-gray-500">Checking SSL, headers, DNS, performance...</p>
        </div>
      )}

      {result && !scanning && (
        <div className="space-y-4">
          <div className={`rounded-xl bg-white border border-gray-200 shadow-sm p-6 ${totalIssues === 0 ? "border-l-4 border-l-emerald-500" : "border-l-4 border-l-amber-500"}`}>
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-xl font-bold">
                  {totalIssues === 0 ? "All Clear" : `${totalIssues} Issues Found`}
                </h2>
                <p className="text-sm text-gray-500">
                  {result.hostname as string} &middot; {modules.length} modules &middot; {result.duration as number}ms
                </p>
              </div>
              <span className={`text-sm font-bold px-3 py-1.5 rounded-full ${
                totalIssues === 0 ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"
              }`}>
                {totalIssues === 0 ? "PASSED" : `${totalIssues} ISSUES`}
              </span>
            </div>
            {totalIssues > 0 && (
              <div className="mt-4 flex gap-2">
                <button
                  onClick={generateFixes}
                  disabled={generatingFixes}
                  className="btn-primary px-4 py-2 text-xs disabled:opacity-50"
                  style={{ background: "#059669" }}
                >
                  {generatingFixes ? "Generating..." : `Generate Fixes`}
                </button>
                <button
                  onClick={runServerScan}
                  className="btn-secondary px-4 py-2 text-xs"
                >
                  Re-scan
                </button>
              </div>
            )}
          </div>

          {/* Generated fixes — ready-to-paste configs */}
          {fixes && Object.keys(fixes).length > 0 && (
            <div className="rounded-xl bg-white border border-gray-200 shadow-sm p-5 border-l-4 border-l-accent">
              <div className="flex items-center gap-2 mb-4">
                <span className="text-accent text-lg">⚡</span>
                <h3 className="font-bold">Ready-to-paste fixes</h3>
              </div>
              <div className="space-y-5">
                {Object.entries(fixes).map(([category, fixList]) => (
                  <div key={category}>
                    <h4 className="font-semibold text-sm text-gray-800 mb-2">{category}</h4>
                    <div className="space-y-3">
                      {fixList.map((f, idx) => {
                        const id = `${category}-${idx}`;
                        return (
                          <div key={id} className="rounded-lg border border-gray-200 bg-gray-50 overflow-hidden">
                            <div className="flex items-center justify-between px-3 py-2 bg-gray-50 border-b border-gray-200">
                              <div>
                                <div className="text-xs font-bold text-gray-800">{f.platform}</div>
                                <div className="text-xs text-gray-500">{f.title}</div>
                              </div>
                              <button
                                onClick={() => copyCode(f.code, id)}
                                className="btn-secondary px-3 py-1 text-xs"
                              >
                                {copiedCode === id ? "Copied!" : "Copy"}
                              </button>
                            </div>
                            <pre className="p-3 text-xs font-mono text-gray-700 overflow-x-auto whitespace-pre-wrap">{f.code}</pre>
                            <p className="px-3 py-2 bg-amber-50 text-xs text-amber-700 border-t border-amber-200">
                              {f.instructions}
                            </p>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {fixes && Object.keys(fixes).length === 0 && (
            <div className="rounded-xl bg-white border border-gray-200 shadow-sm p-5 border-l-4 border-l-amber-500">
              <p className="text-sm text-gray-500">
                No automated fixes available for these specific issues. They require manual review or infrastructure access.
              </p>
            </div>
          )}

          {modules.map((mod) => {
            const status = mod.status as string;
            const details = (mod.details as string[]) || [];
            return (
              <div key={mod.name as string} className={`rounded-xl bg-white border border-gray-200 shadow-sm p-4 ${
                status === "passed" ? "border-l-4 border-l-emerald-500" :
                status === "warning" ? "border-l-4 border-l-amber-500" :
                "border-l-4 border-l-red-500"
              }`}>
                <div className="flex items-center justify-between mb-2">
                  <span className="font-semibold text-sm text-gray-800">{mod.label as string || mod.name as string}</span>
                  <span className={`text-xs font-bold ${
                    status === "passed" ? "text-emerald-600" : status === "warning" ? "text-amber-600" : "text-red-600"
                  }`}>
                    {status === "passed" ? "PASS" : status === "warning" ? "WARN" : "FAIL"}
                  </span>
                </div>
                {details.length > 0 && (
                  <ul className="space-y-1">
                    {details.map((d, i) => (
                      <li key={i} className={`text-xs font-mono ${
                        d.startsWith("error") ? "text-red-600" :
                        d.startsWith("warning") ? "text-amber-600" :
                        d.startsWith("pass") ? "text-emerald-600" :
                        "text-gray-500"
                      }`}>
                        {d}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            );
          })}
        </div>
      )}
    </>
  );
}
